id: Asimily Asset Info Enrich
inputs: []
name: Asimily Asset Info Enrich
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 57bb609f-322e-4377-8ad0-1504bca2b7bc
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 57bb609f-322e-4377-8ad0-1504bca2b7bc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      macAddr:
        simple: ${incident.asimilydevicemacaddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Asimily Insight
      description: Fetch Asimily Asset information
      id: 43e91be8-7bcb-469f-a87b-8bced0dc9eed
      iscommand: true
      name: asimily-get-assetdetails
      script: Asimily Insight|||asimily-get-assetdetails
      type: regular
      version: -1
    taskid: 43e91be8-7bcb-469f-a87b-8bced0dc9eed
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 250,
        "width": 381,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
description: Default playbook for Asimily Anomaly and CVE incidents. It enriches incidents by running asimily-get-assetdetails to fetch related asset information.
