id: Asimily Asset Info Enrich
inputs: []
name: Asimily Asset Info Enrich
outputs: []
starttaskid: "0"
version: -1
tasks:
  "0":
    id: "0"
    taskid: 57bb609f-322e-4377-8ad0-1504bca2b7bc
    type: start
    task:
      id: 57bb609f-322e-4377-8ad0-1504bca2b7bc
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 96b1a79f-2e70-481b-be96-a08760a451b2
    type: regular
    task:
      id: 96b1a79f-2e70-481b-be96-a08760a451b2
      version: -1
      name: Query asimily-get-asset-details
      description: Fetch Asimily Asset information
      script: '|||asimily-get-asset-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      mac_addr:
        simple: ${incident.asimilydevicemacaddress}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 239
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 7c9a9d64-1ca2-42b6-b193-dd8fa8d48194
    type: title
    task:
      id: 7c9a9d64-1ca2-42b6-b193-dd8fa8d48194
      version: -1
      name: Done
      description: Check whether the values provided in arguments are equal. If either of the arguments are missing, no is returned.
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 424
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 434,
        "width": 381,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
description: Default playbook for Asimily Anomaly and CVE incidents. It enriches incidents by running asimily-get-asset-details to fetch related asset information.
